### ISSUE TITLE
Fix/Error: Not Found - Question Page

### ISSUE THREAD

**Issue by mr4227** [NVMS1709/capstone#95]
Receive following Error message when user requests 'reload' of question page or if user pastes in url address for question page.  This does not occur when user navigates to page from another page.

{ Error: Not found
    at app.use.use (/Users/dinali/FS-Materials/capstone/server/index.js:68:21)
    at Layer.handle [as handle_request] (/Users/dinali/FS-Materials/capstone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/dinali/FS-Materials/capstone/node_modules/express/lib/router/index.js:317:13)
    at /Users/dinali/FS-Materials/capstone/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/dinali/FS-Materials/capstone/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/dinali/FS-Materials/capstone/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/dinali/FS-Materials/capstone/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:115:13)
    at SendStream.emit (events.js:210:7)
    at SendStream.error (/Users/dinali/FS-Materials/capstone/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/dinali/FS-Materials/capstone/node_modules/send/index.js:421:12)
    at onstat (/Users/dinali/FS-Materials/capstone/node_modules/send/index.js:727:26)
    at FSReqWrap.oncomplete (fs.js:153:21) status: 404 }

**Comment by mr4227** [comment]
Error no longer coming up
